[unity_env]
file_path = "unity_env/Banana.app"

[learn.kwargs]
n_episodes = 2000
max_t = 1000
eps_start = 1
eps_end = 0.01
eps_decay = 0.995
model_save_path = "models/checkpoint.pth"

[agent]
gamma = 0.99
tau = 0.001
lr = 0.0005
update_every = 4

[buffer.kwargs]
buffer_size = 100000
batch_size = 64

[qmodel]
class_name = "navigate.QNetwork"

[qmodel.kwargs]
fc1_units = 64
fc2_units = 64
