[default.buffer.kwargs]
buffer_size = 100000
batch_size = 64

[default.agent]
gamma = 0.99
tau = 0.001
lr = 0.0005
update_every = 4

[default.qmodel.kwargs]
fc1_units = 64
fc2_units = 64

[default.qmodel]
class_name = "navigate.QNetwork"

[default.learn.kwargs]
n_episodes = 2000
mat_t = 1000
eps_start = 1
eps_end = 0.01
eps_decay = 0.995

[default.unity_env]
file_path = 'unity_env/Banana.app'